# Generated by Django 4.0.3 on 2022-03-30 01:15
# Esse arquivo deve estar contido em um módulo de migrations
from django.db import migrations

# TODO: Verificar como realizar a data migration
def create_marital_status(self, apps, schema_editor):
    marital_status_list = ['CASADO', 'SOLTEIRO', 'DIVORCIADO', 'VIÚVO']
    MaritalStatus = apps.get_registered_model(app_label='basic', model_name='MaritalStatus')
    for m in marital_status_list:
        marital_status = MaritalStatus()
        marital_status.name = m
        marital_status.save()


class Migration(migrations.Migration):
    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_marital_status)
    ]

    # Outra opção de realizar seed ou data migration:
    # operations = [
    #     migrations.RunSQL(
    #         "INSERT INTO marital_status (name, created_at, modified_at, active) VALUES ('Solteiro', current_timestamp, current_timestamp, true );"),
    #     migrations.RunSQL(
    #         "INSERT INTO marital_status (name, created_at, modified_at, active) VALUES ('Casado', current_timestamp, current_timestamp, true );"),
    #     migrations.RunSQL(
    #         "INSERT INTO marital_status (name, created_at, modified_at, active) VALUES ('Divorciado', current_timestamp, current_timestamp, true );"),
    #     migrations.RunSQL(
    #         "INSERT INTO marital_status (name, created_at, modified_at, active) VALUES ('Viúvo', current_timestamp, current_timestamp, true );"),
    # ]
